name: run generate.py

on:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - "main"
      - "releases/**"
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run generate.py
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python generate.py
